# Generated by Django 4.2.1 on 2023-06-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_cover_img_account_profile_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='hometown',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone',
        ),
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='account',
            name='cover_img',
            field=models.ImageField(default='shit', upload_to='cover_pics/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_img',
            field=models.ImageField(default='shit', upload_to='profile_pics/'),
            preserve_default=False,
        ),
    ]
