# Generated by Django 4.2.1 on 2023-05-24 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment_commented_at_like_liked_at_post_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='followed_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 24, 15, 40, 14, 819998, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
