# Generated by Django 4.2.1 on 2023-05-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_shared_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shareCount',
            field=models.IntegerField(default=0),
        ),
    ]
